"""empty message

Revision ID: 1838110a2bb8
Revises: bf6808bdc978
Create Date: 2022-05-13 16:59:45.534205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1838110a2bb8'
down_revision = 'bf6808bdc978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.drop_constraint('category_user_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_user_id_fkey', 'category', 'user', ['user_id'], ['id'])
    op.drop_table('association')
    # ### end Alembic commands ###
