"""empty message

Revision ID: 21689b9d10a2
Revises: 1838110a2bb8
Create Date: 2022-05-18 15:58:12.732445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21689b9d10a2'
down_revision = '1838110a2bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('task_done', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goal',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'goal_id')
    )
    op.drop_table('selected_category')
    op.drop_table('association')
    op.drop_column('goal', 'is_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='association_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name='association_pkey')
    )
    op.create_table('selected_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['category.id'], name='selected_category_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='selected_category_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='selected_category_pkey')
    )
    op.drop_table('user_goal')
    op.drop_table('task')
    # ### end Alembic commands ###
