"""empty message

Revision ID: 30c1c1dc06c0
Revises: 2d0aea5f04b8
Create Date: 2022-06-03 17:58:39.808290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c1c1dc06c0'
down_revision = '2d0aea5f04b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='user_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_category_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name='user_category_pkey')
    )
    # ### end Alembic commands ###
