"""empty message

Revision ID: 5a0372548f7a
Revises: 8151d461f3a9
Create Date: 2022-05-04 20:16:40.687380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0372548f7a'
down_revision = '8151d461f3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.VARCHAR(length=160), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
