"""empty message

Revision ID: 8151d461f3a9
Revises: 3632624f3846
Create Date: 2022-04-30 00:59:10.520711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8151d461f3a9'
down_revision = '3632624f3846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', '_password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=160),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', '_password',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
