"""empty message

Revision ID: c607195a9c96
Revises: 2f1d1c533959
Create Date: 2022-04-27 23:00:10.938791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c607195a9c96'
down_revision = '2f1d1c533959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'is_done')
    # ### end Alembic commands ###
